marcosschroh/python-schema-registry-client

schema_registry/client/client.py
setup.py

We recently had an issue with some complex schemas. Sounds like error is related to python `mappingproxy` binding. We applied the following change to fix the issue.
The problem could be related to this Python bug https://bugs.python.org/issue34858
Some schemas with complex configuration could not be created due to JSON parsing error.
Valid JSON schemas should be correctly decoded by python module to be forwarded to schema registry.
The following code (called `app.py`) is used to register a complex schema:
```python
import avro
from schema_registry.client import SchemaRegistryClient
SCHEMA_REGISTRY_URL='http://kafka-schema-registry.dev'
SUBJECT = 'my_subject'
data = '''
{
"type": "record",
"name": "visit",
"fields": [
{
"name": "metadata",
"type": {
"type": "record",
"name": …
```

fix(client): Fix mapping proxy error

---

docs/serializer.md

Thank you for writing and sharing this library. I was working through the usage example in Message Serializer documentation and encountered a few typos that prevent it from running all the way through. I've corrected them in this PR.
Errors that were fixed are below...
```
Traceback (most recent call last):
File "example.py", line 2, in <module>
from schema_registry.serializer import MessageSerializer
ModuleNotFoundError: No module named 'schema_registry.serializer'
```
```
Traceback (most recent call last):
File "example.py", line 28, in <module>
message_encoded = message_serializer.encode_record_with_schema(
NameError: name 'message_serializer' is not defined
```
```
Traceback (most recent call last):
File "example.py", line 47, in <module>
"user", user_schema, bad_record)
NameError: …
```

docs: Fix a few typos in the Message Serializer python example that prevent it from running.

---

schema_registry/client/schema.py

Since the serializer's encode with schema method causes
a register of the schema, the schema in the registry will
be updated with the special fastavro hint to signify that
fastavro has already parsed the schema. This can be problematic
in a distributed system since other Python fastavro consumers
will not actually have parsed the schema. This can trigger
a KeyError in fastavro because fastavro maintains a module
level dictionary of all the schemas it has parsed. This will fix #30.

Sets _force to True when parsing schemas

---

setup.py

Add a long_description_content_type according to [this guide](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#including-your-readme-in-your-package-s-metadata) so the ReadMe displays correctly on [Pypi](https://pypi.org/project/python-schema-registry-client/)

Add a long_description_content_type in setup.py

---

schema_registry/serializers/faust_serializer.py
tests/serializer/test_faust_serializer_clean_payload.py

Here is my proposal to fix: https://github.com/marcosschroh/python-schema-registry-client/issues/59
This should handle most of the cases (tuple, list, dict, collections.abc.Sequence, collections.abc.MutableSequence, collections.abc.Mapping, collections.abc.MutableMapping) ,
you mentioned handling `typing.Union` but I don't think we need to do anything to handle this case (it's more an annotation than a real python type).
Also it will not work with hashable type (like `set`) as `Record` aren't hashable.

fix serialization of nested record

---

schema_registry/client/client.py

The `SchemaRegistryClient.subject_to _schema_ids` is treated as a `Mapping[subject, Mapping[schema, schema_id]]`, but the lookup in `SchemaRegistryClient.register` is treated as a `Mapping[subject, Mapping[subject, schema_id]]` and so always misses. This results in a cached schema being registered multiple times.

(fix) Fix client.register cache lookup

---

schema_registry/client/client.py

- the requests library is only used to extract username and password from the url. this
functionality is part of the standard library so use `urlparse` instead.
Fixes: #69

Remove requests library usage

---

CHANGELOG.md
schema_registry/client/client.py
setup.py
tests/client/async_client/test_schema_registration.py
tests/client/sync_client/test_schema_registration.py
tests/conftest.py

This enables the use case where schema registry write access is limited to CI/CD, and runtime access is readonly, at the cost of one extra request to the schema registry in the case where the schema is not registered.
This btw mimics the behaviour of Kafka Connect's Avro deserializer.

Check if schema is registered under subject before trying to register it

---

setup.py

It is standard practice in Python to have libraries use version ranges instead of exact versions, unless there is some special circumstance. I noticed the other dependencies are already unpinned, so here's a change request to do the same for fastavro.

Unpin fastavro dependency

---

schema_registry/client/client.py
schema_registry/client/paths.py
schema_registry/client/schema.py
setup.py
tests/client/async_client/test_schema_registration.py
tests/client/sync_client/test_schema_registration.py

Uses GET /schemas/ids/{schema_id}/versions to retrieve the
list of subject,version pairs a schema ID is registered under.
See https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--schemas-ids-int-%20id-versions

New function: get_schema_subject_versions

---

setup.py

We're able to bump the httpx version higher a little bit up to `0.18`. There is a breaking change in `httpx==0.19`.

Increase HTTPX version

---

.gitignore
Dockerfile
README.md
docker-compose.yaml
schema_registry/client/client.py
schema_registry/client/urls.py
scripts/install
scripts/test
setup.py
tests/client/sync_client/test_http_client.py
tests/conftest.py

In this PR
Major changes
- Add support for python >=3.7
- Add support for httpx>=0.18.2
Minor changes
- Add arg `--python-version` to `scripts/test`
- Teardown after tests by `docker-compose down`
To satisfy latest httpx versions we have to replace UnsetType and UNSET with UseClientDefault, USE_CLIENT_DEFAULT , look at an [issue](https://github.com/encode/httpx/issues/1384) on it and [changelog for httpx=0.18.2](https://github.com/encode/httpx/pull/1690). Also after [httpx=0.16](https://github.com/encode/httpx/pull/1347) closed clients raise a runtime error if attempting to send a request. So we should create new session if the previous session was closed. It's much better to create session on startup and reuse it for all requests, but it is not in the scope of this PR

add support for python 3.7+ and latest httpx

---

docs/client.md
schema_registry/client/client.py
schema_registry/client/schema.py
schema_registry/client/urls.py
schema_registry/serializers/__init__.py
schema_registry/serializers/message_serializer.py
setup.py
tests/client/async_client/test_http_client.py
tests/client/sync_client/test_http_client.py
tests/conftest.py
tests/serializer/test_async_message_serializer.py
tests/serializer/test_faust_serializer.py
tests/serializer/test_message_serializer.py

I made this PR for two reasons. 
-  With time, if we want to make this library adoptable for newer services, we need to evolve it alongside its dependencies. It's currently not compatible with the latest version of `httpx`. From `0.19.0` upward.
- Secondly, Httpx made some updates to newer versions of httpx. These updates include the efficient use of network resources. They [recommend using http Client as a context manager ](https://www.python-httpx.org/advanced/)as it ensures connections are properly cleaned up when leaving the “with” block.

Provide support newer versions of httpx

---

docs/faust.md

Add documentation to add codec to `pyproject.toml` when using poetry.

doc(faust): add codec to `pyproject.toml`

---

setup.py

@marcosschroh , I apologize. I didn't fully vet the change for the py.typed marker earlier.
This PR moves the file to the schema_registry package and adds it to the package_data in setup.py. This ensures that the file will be available for type-checking when installed via pypi.
It has been verified locally and against a test-repostory on pypi,

fix location of py.typed marker, and include as package_data in setup.py

---

pyproject.toml
schema_registry/client/__init__.py
schema_registry/client/auth_utils.py
schema_registry/client/client.py
tests/client/async_client/test_http_client.py
tests/client/sync_client/test_http_client.py

Addresses #173 
This replaces the `schema_registry.auth_utils.Auth` class with `httpx.Auth`. This enables others to supply their own authentication logic in addition to `httpx.BasicAuth`
The current API/functionality of parsing the URL to determine the username/password has been maintained

Add support for generic httpx.Auth 

---

schema_registry/serializers/message_serializer.py

Was this print statement added on purpose? It causes a bit of noise in our logs. Would you consider removing it?

remove print statement from serializer

---

schema_registry/client/client.py
tests/client/async_client/test_schema_version.py
tests/client/sync_client/test_schema_version.py

Some calls to the SchemaVersion constructor swapped the order of the schema and version args. I switched them all to use kwargs to eliminate the problem.

fix order of arguments in SchemaVersion constructor

---

README.md
pyproject.toml

Hey,
I noticed there is still some reference to python3.7 but it has been dropped previously so just cleaning !

build(py37): remove python 3.7  reference

---

poetry.lock
pyproject.toml

Hey,
I opened this PR related to this issue: https://github.com/marcosschroh/python-schema-registry-client/issues/243

fix(dependencies): change httpx version constraints to allow 0.*

---

poetry.lock
pyproject.toml
schema_registry/serializers/faust.py
scripts/format
scripts/test
tests/client/async_client/test_schema_registration.py
tests/client/sync_client/test_schema_registration.py

Hey,
I noticed some warning in pyproject.toml due to change from ruff `0.0.*` -> `0.2.*`, I fixed it and updated the poetry.lock. I'm not usually working with poetry so I may be wrong :pray: 
Also this PR contains:
- `mypy` configuration removed as it seems not valid, in case it was I could revert changes
Question:
- Ruff version 0.2 comes with a formatter which could replace black, do you want me to include this change inside this PR ?
- I tried to run the project under a python3.12 install and the `poetry install` failed to install due to `pyyaml 6.0.0`. I cleaned the poetry.lock and did a fresh install and got `pyyaml 6.0.1` which brings for py3.12. Should I create a new PR with this ?

build(dependencies): update ruff to 0.2.1 in poetry-lock and pyproject.toml

---

poetry.lock
schema_registry/client/client.py
schema_registry/client/schema.py
schema_registry/serializers/faust.py
schema_registry/serializers/message_serializer.py

I bumped fastavro as the [PR here](https://github.com/marcosschroh/python-schema-registry-client/pull/233
) and fixed the CI.
I dived into `fastavro.schema.parse_schema` to understand typing result:
- It takes a `Schema` which is an alias of `Union[str, List, DictSchema]`
- And if we pass schema type as the following:
1. `str` it returns a `str | List`.
2. `dict` it returns a `dict`.
3. `list` it returns a `list` and nested types will be as defined previously.
And also cleaned some `type: ignore`

build(deps): bump fastavro to 1.9.3 and correct typing

---

.github/workflows/docs-preview.yaml
.github/workflows/docs-publish.yaml
.github/workflows/publish.yaml
.github/workflows/python-package.yml
pyproject.toml

And finally : add support for python3.12 ! In the end nothing much to do as the ci locally passed:
- Added declaration in pyproject.toml 
- Added to "3.12" to the matrix in CI
- Switched default build to 3.12 instead of 3.11 (I could rollback this if you are not sure about it)

build: add python3.12 support and update CI

---

schema_registry/client/client.py
tests/client/sync_client/test_http_client.py
tests/client/sync_client/test_schema_compatibility.py
tests/conftest.py

The schema-registry proposes a [`verbose` option][1] to retrieve the details, but that isn't available in this python client
Add an option in the python client to retrieve the details in case of incompatiblity
- send the parameter `verbose` to the schema-registry API
- return the full JSON response if `verbose=True`
Closes https://github.com/marcosschroh/python-schema-registry-client/issues/337
[1]: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--compatibility-subjects-(string-%20subject)-versions-(versionId-%20version)

Add verbose option for test_compatibility
